name: CI/CD-Sandbox

on:
  push:
    branches:
      - sandbox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Maximum execution time

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0" # Adjust the Flutter version as needed

      - name: Build and Deploy
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter build web --profile

      - name: Check for Build Errors
        id: build-status
        run: |
          if [ -d "build/web" ]; then
            echo "Build succeeded (sandbox)."
          else
            echo "Build failed (sandbox). Trying to recover..."
            flutter clean
            dart run build_runner build --delete-conflicting-outputs
            flutter build web --profile
          fi

      - name: Archive Build Artifacts
        if: steps.build-status.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: web-artifact
          path: build/web
          retention-days: 15 # Will be expired in 15 days

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          production-deploy: true
          publish-dir: '${{ github.workspace }}/build/web'
          deploy-message: "Deploy from CI-CD"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 4
