name: CI/CD-Sandbox

on:
  push:
    branches:
      - sandbox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Maximum execution time

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0" # Adjust the Flutter version as needed

      - name: Build and Deploy
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter build web --profile

      - name: Check for Build Errors
        id: build-status
        run: |
          if [ -d "build/web" ]; then
            echo "Build succeeded (sandbox)."
          else
            echo "Build failed (sandbox). Trying to recover..."
            flutter clean
            dart run build_runner build --delete-conflicting-outputs
            flutter build web --profile
          fi

      - name: Archive Build Artifacts
        if: steps.build-status.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: web-artifact
          path: build/web
          retention-days: 15 # Will be expired in 15 days

      - name: Deploy to EC2
        if: steps.build-status.outcome == 'success'
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}/sandbox/demo
          SOURCE: build/
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PEM_KEY }}
          SCRIPT_AFTER: |
            echo "Running script..."

            path="/home/ubuntu/web"

            artifact_path="${{ secrets.TARGET }}/sandbox/demo/web"

            echo "Deleting web/ folder"
            rm -rf ${path}/web

            # Ensure that $GITHUB_WORKSPACE exists
            echo "checking if artifact exists"
            if [ -d "${artifact_path}" ]; then
              echo "Artifact exists"
              cp -r ${artifact_path} ${path}/web
              echo "Transferred ${artifact_path} to ${path}/web"
            else
              echo "Artifact does not exist. Nothing to copy"
            fi
